### ISSUE TITLE
Create Backend with Node.JS

### ISSUE THREAD

**Issue by samueltoloruntomi** [samueltoloruntomi/Student-Rent#4]

**Comment by dannysheridan** [comment]
@samueltoloruntomi  have you considered going schema-first and auto-generating the networking logic & types on the backend? our open source project supports Express if that's the server framework you've picked: www.buildwithfern.com

**Comment by samueltoloruntomi** [comment]
Thank you, significant progress has been made using the express framework and this task is completed and issue is now closed, Thank you for reaching out @dannysheridan
